name: GameEngine
version: 1.0
main: com.laudynetwork.gameengine.GameEngine
api-version: '1.20'
authors:
  - DasShorty

dependencies:
  - name: NetworkUtils
    required: true

load-after:
  - name: NetworkUtils